INSERT INTO FOOD (NAME, QUANTITY, CREATED_AT, MODIFIED_AT)
VALUES ( 'FOOD1', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO FOOD (NAME, QUANTITY, CREATED_AT, MODIFIED_AT)
VALUES ( 'FOOD2', 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );