DROP TABLE IF EXISTS FOOD;
CREATE TABLE FOOD (
    ID UUID default random_uuid(),
    NAME varchar(255) NOT NULL,
    QUANTITY int NOT NULL,
    CREATED_AT DATE NOT NULL,
    MODIFIED_AT DATE NOT NULL,
    PRIMARY KEY (ID)
);